// <auto-generated />
using System;
using Diary_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diary_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828202204_seedingDataDiaryEntry")]
    partial class seedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diary_App.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = " Went to Diving with joe",
                            Created = new DateTime(2025, 8, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Went to Diving"
                        },
                        new
                        {
                            Id = 2,
                            Content = " Went to Diving with joe",
                            Created = new DateTime(2025, 8, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Went to Diving"
                        },
                        new
                        {
                            Id = 3,
                            Content = " Went to Diving with joe",
                            Created = new DateTime(2025, 8, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Went to Diving"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
