// <auto-generated />
using System;
using ETickets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETickets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919151046_AddedSeedingData")]
    partial class AddedSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 3,
                            MoviesId = 3
                        });
                });

            modelBuilder.Entity("ETickets.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "This is the bio for the first actor",
                            FullName = "Actor 1",
                            ProfilePicture = "actor1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "This is the bio for the second actor",
                            FullName = "Actor 2",
                            ProfilePicture = "actor2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "This is the bio for the third actor",
                            FullName = "Actor 3",
                            ProfilePicture = "actor3.jpg"
                        });
                });

            modelBuilder.Entity("ETickets.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the description for the first cinema",
                            Logo = "cinema1.jpg",
                            Name = "Cinema 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is the description for the second cinema",
                            Logo = "cinema3.jpg",
                            Name = "Cinema 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is the description for the third cinema",
                            Logo = "cinema3.jpg",
                            Name = "Cinema 3"
                        });
                });

            modelBuilder.Entity("ETickets.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            Description = "This is the description of first movie",
                            EndDate = new DateTime(2025, 9, 26, 20, 10, 44, 901, DateTimeKind.Local).AddTicks(3240),
                            Image = "movie1.jpg",
                            MovieCategory = 0,
                            Name = "Movie 1",
                            Price = 30.0,
                            ProducerId = 2,
                            StartDate = new DateTime(2025, 9, 19, 20, 10, 44, 899, DateTimeKind.Local).AddTicks(7878)
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 2,
                            Description = "This is the description of second movie",
                            EndDate = new DateTime(2025, 9, 26, 20, 10, 44, 901, DateTimeKind.Local).AddTicks(3732),
                            Image = "movie2.jpg",
                            MovieCategory = 2,
                            Name = "Movie 2",
                            Price = 45.0,
                            ProducerId = 2,
                            StartDate = new DateTime(2025, 9, 19, 20, 10, 44, 901, DateTimeKind.Local).AddTicks(3729)
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 3,
                            Description = "This is the description of third movie",
                            EndDate = new DateTime(2025, 9, 26, 20, 10, 44, 901, DateTimeKind.Local).AddTicks(3739),
                            Image = "movie3.jpg",
                            MovieCategory = 0,
                            Name = "Movie 3",
                            Price = 40.0,
                            ProducerId = 3,
                            StartDate = new DateTime(2025, 9, 19, 20, 10, 44, 901, DateTimeKind.Local).AddTicks(3738)
                        });
                });

            modelBuilder.Entity("ETickets.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "This is the bio for the first Producer",
                            FullName = "Producer 1",
                            ProfilePicture = "producer1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "This is the bio for the second Producer",
                            FullName = "Producer 2",
                            ProfilePicture = "producer2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "This is the bio for the third Producer",
                            FullName = "Producer 3",
                            ProfilePicture = "producer3.jpg"
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("ETickets.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETickets.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ETickets.Models.Movie", b =>
                {
                    b.HasOne("ETickets.Models.Cinema", "Cinema")
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETickets.Models.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("ETickets.Models.Cinema", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("ETickets.Models.Producer", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
